# Generated by Django 4.1.7 on 2024-05-04 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wine',
            name='image',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
