# Generated by Django 4.1.7 on 2024-05-04 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_wine_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wine',
            old_name='image',
            new_name='thumbnail',
        ),
    ]
